[package]
name = "mythic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = { version = "0.4.45", features = ["serde"] }
const_format = "0.2.36"
dirs = "7.0.0"
env_logger = "0.11.11"
iced = { version = "0.14.0", features = ["image"] }
iced_graphics = { version = "0.14.0", features = ["geometry", "image", "svg", "web-colors"], default-features = false }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
isahc = { version = "2.0.1", features = ["json"] }
log = "0.4.34"
open = "5.4.4"
serde = { version = "1.0.229", features = ["derive", "rc"] }
serde_json = "1.0.151"
serde_url_params = "0.2.1"
smart-default = "0.7.1"
toml = "1.1.6"
url = "2"
rkyv = { version = "0.8", default-features = false, features = ["std", "alloc", "hashbrown-0_14"] }

[build-dependencies]
winres = "0.1"

[profile.test]
inherits = "release"
