query getGameDetails($locale: String!, $sandboxId: String!) {
    Product {
        sandbox(sandboxId: $sandboxId) {
            configuration(locale: $locale, templateId: null) {
                ... on HomeConfiguration {
                    configs {
                        longDescription
                    }
                }
                ... on StoreConfiguration {
                    configs {
                        criticReviews {
                            openCritic
                        }
                        externalPlatformLaunchOptions {
                            xCloud {
                                linkSrc
                                type
                            }
                        }
                        gameWebsite
                        privacyLink
                        socialLinks {
                            platform
                            url
                        }
                        supportedAudio
                        supportedText
                        tags(locale: $locale) {
                            id
                            name
                            groupName
                        }
                        technicalRequirements {
                            macos {
                                minimum
                                recommended
                                title
                            }
                            windows {
                                minimum
                                recommended
                                title
                            }
                        }
                    }
                }
            }
        }
    }
}
