name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_LTO: true
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: main
        add-rust-environment-hash-key: true
    - name: Build release
      run: cargo build --locked --release --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v7.0.1
      with:
        name: Windows x86-64
        path: target/release/mythic.exe
        archive: false
    - name: Run tests
      run: cargo test --locked --verbose
